#!/bin/bash

if [ "$1" == "init" ]; then
    exec xterm -fullscreen -fa 'Monospace' -fs 9 -e sdlSpeedometer-stat
fi

tmpfile=$(mktemp /tmp/stat.XXXXXX)

doTouch()
{
    while (true) do 
        evtest --query  /dev/input/event0 EV_KEY BTN_TOUCH
        if [ $? -ne 0 ]; then
            rm -f $tmpfile
            exit 0
        fi
        sleep 0.5
    done

}

doTouch &

if [ -n "$(/usr/bin/which hciconfig)" ]; then
    if hciconfig hci0 &>/dev/null; then
        hcicmd="true"
    fi
fi

while (true) do 
    clear
    top -n 1 | grep -A5 PID | egrep -v 'top|0,0   0'
    echo "--"
    ifconfig | grep -A3 flags |  egrep -v 'inet6|lo:|127|loop'
    if [ -n "$hcicmd" ]; then
        echo "--"
        hciconfig lestates | egrep -v 'BD'
    fi
    echo "--"
    uptime
    echo "--"
    echo "CPU temp=$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))"
    echo "--"
    echo "Tap screen to exit"
    sleep 4
    if [ ! -e $tmpfile ]; then
        break
    fi
done
