#!/bin/bash
ip=$(ifconfig eth0 | grep netmask | awk '{printf $2}')
port=80
# This example requires that websocketNmea is running on the desired host I.P eth0.
# See: https://github.com/ehedman/websocketNmea


/usr/bin/chromium \
  --no-sandbox \
  --password-store=basic \
  --noerrdialogs \
  --disable-infobars \
  --kiosk \
  http://"${ip}":"${port}"/navi/victron-gui-v2.php

