#!/bin/bash
ip=$(ifconfig eth0 | grep netmask | awk '{printf $2}')
port=80
# This example requires that vicron venus is running on the desired host I.P eth0.
# See: https://github.com/ehedman/victron-venus-container

# Temporary profile directory
PROFILE=/tmp/chromium-profile/$(id -u)

# Remove previous profile and create new skeleton
rm -rf "$PROFILE"
mkdir -p "$PROFILE/Default"

# Launch Chromium in Cage kiosk
/usr/bin/chromium \
  --in-process-gpu \
  --enable-gpu-rasterization \
  --disable-background-networking \
  --disable-sync \
  --disable-features=TranslateUI \
  --no-sandbox \
  --no-first-run \
  --kiosk \
  --user-data-dir="$PROFILE" \
  --disk-cache-size=0 \
  --disable-extensions \
  --disable-component-extensions-with-background-pages \
  --disable-plugins \
  --disable-plugins-discovery \
  --disable-translate \
  --incognito \
  --single-process \
  http://"${ip}":"${port}"/navi/victron-gui-v2.php &>/tmp/junk

