#!/bin/bash
# This example requires that websocketNmea is running on the desired host I.P
# See: https://github.com/ehedman/websocketNmea
/usr/bin/chromium-browser --noerrdialogs --disable-infobars --kiosk --force-device-scale-factor=1.2 http://127.0.1/navi/npanel.php?bar=1  &>/dev/null
