#!/bin/bash
ip=$(ifconfig eth0 | grep netmask | awk '{printf $2}')
port=$(cat $(ps -ef | grep lighttpd | awk '/conf/{print $NF}') | awk '/server.port/{print $NF; exit}')
# This example requires that websocketNmea is running on the desired host I.P eth0.
# See: https://github.com/ehedman/websocketNmea

/usr/bin/chromium \
  --no-sandbox \
  --password-store=basic \
  --noerrdialogs \
  --disable-infobars \
  --kiosk \
  --force-device-scale-factor=0.5 \
  --use-gl=egl \
  --use-angle=default \
  --enable-gpu-rasterization \
  http://"${ip}":"${port}"/navi/npanel.php?compact=1
