#!/bin/bash

# Start a single session X-or an openvt bound application

PATH=$PATH:$(pwd)
export PATH

program=$1

app=$(which "${program}")

if [ -z "${app}" ]; then
    exit 1
fi

trap doQuit INT

function doQuit() {
    if [ -n "${XPID}" ]; then
        kill -INT "${XPID}"
    fi
    exit 0
}

if [ "$(basename "${app}")" == "openvt" ]; then
    shift
    openvt -w -s "$@"
    exit 0
fi

export DISPLAY=:0.0

function setDisplay() {
    sleep 5
    xset -dpms
    xset s off
    xset s noblank
}

if ! pidof -s Xorg &>/dev/null; then
    Xorg -nolisten tcp vt7 -nocursor -novtswitch  -quiet &> /dev/null &
    XPID=$!
fi

let q=5

shift

if [ -n "${XPID}" ]; then
    while xset q &>/dev/null ; [ $? -ne 0 ]; do
        sleep 1
        let "q--"
        if [ $q -le 0 ]; then
           doQuit
        fi
    done
fi 

setDisplay &

${app} "$@" &>/dev/null

doQuit
