#!/bin/bash

# Start a single session X-or an openvt bound application

PATH=$PATH:$(pwd)
export PATH

program=$1

app=$(which "${program}")

if [ -z "${app}" ]; then
    exit 1
fi

function doQuit() {

    if [ -n "${XPID}" ]; then
        kill -INT "${XPID}" &>/dev/null
    fi

    if [ -n "${APPID}" ]; then
        kill -INT "${APPID}" &>/dev/null
    fi

    exit 0
}

trap doQuit EXIT

if [ "$(basename "${app}")" == "openvt" ]; then
    shift
    openvt -w -s "$@"
    exit 0
fi


function setDisplay() {
    xset -dpms
    xset s off
    xset s noblank
}

if ! pidof -s Xorg &>/dev/null; then
    Xorg -nolisten tcp vt7 -nocursor -novtswitch -quiet &> /dev/null &
    XPID=$!
fi

let q=5

shift

export DISPLAY=:0.0

if [ -n "${XPID}" ]; then
    while xrandr -s "${WINDOW_W}"x"${WINDOW_H}" &>/dev/null ; [ $? -ne 0 ]; do
        sleep 1
        let "q--"
        if [ $q -le 0 ]; then
           doQuit
        fi
    done
fi 

setDisplay &

function  startChild()
{
    exec ${app} "$@" &>/dev/null
}

startChild "$@" &
APPID=$!
wait $APPID

doQuit
