[core]
shell=kiosk-shell.so
idle-time=0
xwayland=true

[shell]
locking=false
panel-position=none

[output]
name=HDMI-A-1
mode=800x480
force-on=true

[vnc]
address=0.0.0.0

[output]
name=vnc
#mode=800x480
mirror-of=HDMI-A-1
